apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-auth0-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  API_VERSION: "1.0"
  POD_NAME: "go-auth0.k8-v.2.0"
  PORT: "5100"
  SETPOD_AZ: "false"
  USER_TABLE_NAME: user_login_2
  #JWT_KEY: "my_secret_key"
  #SSM_JWT_KEY: "key-secret"
  OTEL_EXPORTER_OTLP_ENDPOINT: "arch-eks-02-xray-collector.default.svc.cluster.local:4317"
  ENV: "dev"
  SECRET_NAME_H256: "key_jwt_sa"